### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by boychuk-ol** [OS-IS/ai202-bojchuk#1]

**Comment by boychuk-ol** [comment]
![git_push_token](https://github.com/user-attachments/assets/6d6e00aa-f120-43db-b8ba-f59963a1aa37)

**Comment by boychuk-ol** [comment]
![SSH1](https://github.com/user-attachments/assets/cd65fbb0-ab12-4b4e-97b3-0cba76a14c5c)
![ssh2](https://github.com/user-attachments/assets/bbd67ccf-217b-4f83-ac1d-37cce326cf27)

**Comment by boychuk-ol** [comment]
![weqw](https://github.com/user-attachments/assets/75f402a9-5a77-4bc8-baff-91b9d748b442)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів
