### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai202-bojchuk#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
7) Відомо, що з серпня 2021 року GitHub-сервер пропонує PAT 
для процесу клонування Private GitHub-репозиторіїв. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by boychuk-ol** [comment]
Це було зроблено для підвищення безпеки
Токени дозволяють зберегти та використовувати єдиний стандарт автентифікації на всіх рівнях роботи з GitHub
На відміну від звичайних паролів, токени більш захищені і мають обмежений термін дії, ризик від використання PAT значно нижчий, ніж при передачі пароля

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
